### ISSUE TITLE
Error 500 with docker-compose

### ISSUE THREAD

**Issue by chdecultot** [ivadim/fruitnanny#17]
Hi,

Thanks a lot for this software!
I'm trying to run it with docker-compose but I have a 500 error whenever I want to want to connect to the application from my local network:
![image](https://user-images.githubusercontent.com/4903591/67659497-c17ccd80-f95c-11e9-9bbc-260a1930b840.png)

When I try to connect directly to port 7000, I get the following error:
![image](https://user-images.githubusercontent.com/4903591/67659551-e7a26d80-f95c-11e9-8121-39a48c618862.png)

Here are the extended logs when launching docker-compose up:
```
Starting fruitnanny_janus_1 ... done
Starting fruitnanny_gstreamer-video_1 ... done
Starting fruitnanny_gstreamer-audio_1 ... done
Starting fruitnanny_fruitnanny_1      ... done
Starting fruitnanny_nginx_1           ... done
Attaching to fruitnanny_janus_1, fruitnanny_gstreamer-video_1, fruitnanny_fruitnanny_1, fruitnanny_gstreamer-audio_1, fruitnanny_nginx_1
fruitnanny_1       | Fruitnanny app listening on port 7000!
janus_1            | Janus commit: not-a-git-repo
janus_1            | Compiled on:  Tue Feb 12 11:25:05 UTC 2019
janus_1            | 
gstreamer-video_1  | Setting pipeline to PAUSED ...
gstreamer-video_1  | Pipeline is live and does not need PREROLL ...
gstreamer-video_1  | /GstPipeline:pipeline0/GstRpiCamSrc:src.GstPad:src: caps = video/x-h264, width=(int)960, height=(int)540, framerate=(fraction)12/1, stream-format=(string)byte-stream, alignment=(string)nal, profile=(string)constrained-baseline
gstreamer-video_1  | /GstPipeline:pipeline0/GstCapsFilter:capsfilter0.GstPad:src: caps = video/x-h264, width=(int)960, height=(int)540, framerate=(fraction)12/1, stream-format=(string)byte-stream, alignment=(string)nal, profile=(string)constrained-baseline
gstreamer-video_1  | /GstPipeline:pipeline0/GstQueue:queue0.GstPad:src: caps = video/x-h264, width=(int)960, height=(int)540, framerate=(fraction)12/1, stream-format=(string)byte-stream, alignment=(string)nal, profile=(string)constrained-baseline
gstreamer-video_1  | /GstPipeline:pipeline0/GstH264Parse:h264parse0.GstPad:sink: caps = video/x-h264, width=(int)960, height=(int)540, framerate=(fraction)12/1, stream-format=(string)byte-stream, alignment=(string)nal, profile=(string)constrained-baseline
gstreamer-video_1  | /GstPipeline:pipeline0/GstQueue:queue0.GstPad:sink: caps = video/x-h264, width=(int)960, height=(int)540, framerate=(fraction)12/1, stream-format=(string)byte-stream, alignment=(string)nal, profile=(string)constrained-baseline
gstreamer-video_1  | /GstPipeline:pipeline0/GstCapsFilter:capsfilter0.GstPad:sink: caps = video/x-h264, width=(int)960, height=(int)540, framerate=(fraction)12/1, stream-format=(string)byte-stream, alignment=(string)nal, profile=(string)constrained-baseline
gstreamer-video_1  | Setting pipeline to PLAYING ...
gstreamer-video_1  | New clock: GstSystemClock
gstreamer-video_1  | /GstPipeline:pipeline0/GstH264Parse:h264parse0.GstPad:src: caps = video/x-h264, width=(int)960, height=(int)540, framerate=(fraction)12/1, stream-format=(string)avc, alignment=(string)au, profile=(string)constrained-baseline, interlace-mode=(string)progressive, chroma-format=(string)4:2:0, bit-depth-luma=(uint)8, bit-depth-chroma=(uint)8, parsed=(boolean)true, level=(string)4, codec_data=(buffer)0142c028ffe1000e2742c02895a03c045fb80789135001000528ce025c80
gstreamer-video_1  | /GstPipeline:pipeline0/GstRtpH264Pay:rtph264pay0.GstPad:src: caps = application/x-rtp, media=(string)video, clock-rate=(int)90000, encoding-name=(string)H264, packetization-mode=(string)1, profile-level-id=(string)42c028, sprop-parameter-sets=(string)"J0LAKJWgPARfuAeJE1A\=\,KM4CXIA\=", payload=(int)96, ssrc=(uint)3648240313, timestamp-offset=(uint)526674995, seqnum-offset=(uint)1591, a-framerate=(string)12
gstreamer-video_1  | /GstPipeline:pipeline0/GstQueue:queue1.GstPad:src: caps = application/x-rtp, media=(string)video, clock-rate=(int)90000, encoding-name=(string)H264, packetization-mode=(string)1, profile-level-id=(string)42c028, sprop-parameter-sets=(string)"J0LAKJWgPARfuAeJE1A\=\,KM4CXIA\=", payload=(int)96, ssrc=(uint)3648240313, timestamp-offset=(uint)526674995, seqnum-offset=(uint)1591, a-framerate=(string)12
gstreamer-video_1  | /GstPipeline:pipeline0/GstRtpH264Pay:rtph264pay0: timestamp = 526674995
gstreamer-video_1  | /GstPipeline:pipeline0/GstRtpH264Pay:rtph264pay0: seqnum = 1591
gstreamer-video_1  | /GstPipeline:pipeline0/GstQueue:queue1.GstPad:src: caps = application/x-rtp, media=(string)video, clock-rate=(int)90000, encoding-name=(string)H264, packetization-mode=(string)1, profile-level-id=(string)42c028, sprop-parameter-sets=(string)"J0LAKJWgPARfuAeJE1A\=\,KM4CXIA\=", payload=(int)96, ssrc=(uint)3648240313, timestamp-offset=(uint)526674995, seqnum-offset=(uint)1591, a-framerate=(string)12
gstreamer-video_1  | /GstPipeline:pipeline0/GstUDPSink:udpsink0.GstPad:sink: caps = application/x-rtp, media=(string)video, clock-rate=(int)90000, encoding-name=(string)H264, packetization-mode=(string)1, profile-level-id=(string)42c028, sprop-parameter-sets=(string)"J0LAKJWgPARfuAeJE1A\=\,KM4CXIA\=", payload=(int)96, ssrc=(uint)3648240313, timestamp-offset=(uint)526674995, seqnum-offset=(uint)1591, a-framerate=(string)12
janus_1            | ---------------------------------------------------
janus_1            |   Starting Meetecho Janus (WebRTC Server) v0.6.1
janus_1            | ---------------------------------------------------
janus_1            | 
janus_1            | Checking command line arguments...
janus_1            | Debug/log level is 4
janus_1            | Debug/log timestamps are disabled
janus_1            | Debug/log colors are disabled
janus_1            | Adding 'vmnet' to the ICE ignore list...
janus_1            | Using 192.168.1.65 as local IP...
janus_1            | [WARN] Token based authentication disabled
janus_1            | Initializing recorder code
janus_1            | Initializing ICE stuff (Full mode, ICE-TCP candidates disabled, half-trickle, IPv6 support disabled)
janus_1            | TURN REST API backend: (disabled)
janus_1            | [WARN] Janus is deployed on a private address (192.168.1.65) but you didn't specify any STUN server! Expect trouble if this is supposed to work over the internet and not just in a LAN...
janus_1            | Crypto: OpenSSL >= 1.1.0
janus_1            | [WARN] The libsrtp installation does not support AES-GCM profiles
janus_1            | Fingerprint of our certificate: 13:41:D3:0C:4F:BF:C4:AB:F7:FE:59:66:08:E5:16:8F:17:5A:3B:3B:D5:73:C6:83:85:8B:7F:DD:1F:C2:EC:B2
janus_1            | [WARN] Event handlers support disabled
janus_1            | Plugins folder: /usr/lib/arm-linux-gnueabihf/janus/plugins
janus_1            | [WARN] Plugin 'libjanus_duktape.so' has been disabled, skipping...
janus_1            | [WARN] Plugin 'libjanus_videoroom.so' has been disabled, skipping...
janus_1            | [WARN] Plugin 'libjanus_sipre.so' has been disabled, skipping...
janus_1            | [WARN] Plugin 'libjanus_lua.so' has been disabled, skipping...
janus_1            | [WARN] Plugin 'libjanus_videocall.so' has been disabled, skipping...
janus_1            | [WARN] Plugin 'libjanus_recordplay.so' has been disabled, skipping...
janus_1            | [WARN] Plugin 'libjanus_sip.so' has been disabled, skipping...
janus_1            | Joining Janus requests handler thread
janus_1            | [WARN] Plugin 'libjanus_audiobridge.so' has been disabled, skipping...
janus_1            | Loading plugin 'libjanus_streaming.so'...
janus_1            | Sessions watchdog started
janus_1            | JANUS Streaming plugin initialized!
janus_1            | [WARN] Plugin 'libjanus_voicemail.so' has been disabled, skipping...
janus_1            | [WARN] Plugin 'libjanus_echotest.so' has been disabled, skipping...
janus_1            | [WARN] Plugin 'libjanus_textroom.so' has been disabled, skipping...
janus_1            | [WARN] Plugin 'libjanus_nosip.so' has been disabled, skipping...
janus_1            | Transport plugins folder: /usr/lib/arm-linux-gnueabihf/janus/transports
janus_1            | [WARN] Transport plugin 'libjanus_rabbitmq.so' has been disabled, skipping...
janus_1            | [WARN] Transport plugin 'libjanus_nanomsg.so' has been disabled, skipping...
janus_1            | Loading transport plugin 'libjanus_websockets.so'...
janus_1            | [2019/10/28 07:39:34:6145] NOTICE: lws_context_destroy
janus_1            | [WARN] libwebsockets has been built without IPv6 support, will bind to IPv4 only
janus_1            | [ERR] [config.c:janus_config_parse:191]   -- Error reading configuration file 'janus.transport.websockets.jcfg'... error 2 (No such file or directory)
janus_1            | [WARN] Couldn't find .jcfg configuration file (janus.transport.websockets), trying .cfg
janus_1            | [ERR] [config.c:janus_config_parse:191]   -- Error reading configuration file 'janus.transport.websockets.cfg'... error 2 (No such file or directory)
janus_1            | [WARN] No WebSockets server started, giving up...
janus_1            | [WARN] The 'janus.transport.websockets' plugin could not be initialized
janus_1            | Loading transport plugin 'libjanus_http.so'...
janus_1            | HTTP webserver started (port 8088, /janus path listener)...
janus_1            | HTTPS webserver started (port 8089, /janus path listener)...
janus_1            | [WARN] Admin/monitor HTTP webserver disabled
janus_1            | [WARN] Admin/monitor HTTPS webserver disabled
janus_1            | JANUS REST (HTTP/HTTPS) transport plugin initialized!
janus_1            | [WARN] Transport plugin 'libjanus_pfunix.so' has been disabled, skipping...
janus_1            | [fruitnanny] New audio stream! (ssrc=4178282910)
janus_1            | [fruitnanny] New video stream! (ssrc=3648240313, index 0)
gstreamer-audio_1  | Setting pipeline to PAUSED ...
gstreamer-audio_1  | Pipeline is live and does not need PREROLL ...
gstreamer-audio_1  | Setting pipeline to PLAYING ...
gstreamer-audio_1  | New clock: GstAudioSrcClock
gstreamer-audio_1  | /GstPipeline:pipeline0/GstAlsaSrc:alsasrc0: actual-buffer-time = 200000
gstreamer-audio_1  | /GstPipeline:pipeline0/GstAlsaSrc:alsasrc0: actual-latency-time = 10000
gstreamer-audio_1  | Redistribute latency...
gstreamer-audio_1  | /GstPipeline:pipeline0/GstAlsaSrc:alsasrc0.GstPad:src: caps = audio/x-raw, rate=(int)48000, channels=(int)1, format=(string)S16LE, layout=(string)interleaved
gstreamer-audio_1  | /GstPipeline:pipeline0/GstAudioConvert:audioconvert0.GstPad:src: caps = audio/x-raw, rate=(int)48000, channels=(int)1, format=(string)S16LE, layout=(string)interleaved
gstreamer-audio_1  | /GstPipeline:pipeline0/GstAudioResample:audioresample0.GstPad:src: caps = audio/x-raw, rate=(int)48000, channels=(int)1, format=(string)S16LE, layout=(string)interleaved
gstreamer-audio_1  | /GstPipeline:pipeline0/GstOpusEnc:opusenc0.GstPad:sink: caps = audio/x-raw, rate=(int)48000, channels=(int)1, format=(string)S16LE, layout=(string)interleaved
gstreamer-audio_1  | /GstPipeline:pipeline0/GstAudioResample:audioresample0.GstPad:sink: caps = audio/x-raw, rate=(int)48000, channels=(int)1, format=(string)S16LE, layout=(string)interleaved
gstreamer-audio_1  | /GstPipeline:pipeline0/GstAudioConvert:audioconvert0.GstPad:sink: caps = audio/x-raw, rate=(int)48000, channels=(int)1, format=(string)S16LE, layout=(string)interleaved
gstreamer-audio_1  | Redistribute latency...
gstreamer-audio_1  | /GstPipeline:pipeline0/GstOpusEnc:opusenc0.GstPad:src: caps = audio/x-opus, rate=(int)48000, channels=(int)1, channel-mapping-family=(int)0, stream-count=(int)1, coupled-count=(int)0, streamheader=(buffer)< 4f707573486561640101380180bb0000000000, 4f707573546167731e000000456e636f6465642077697468204753747265616d6572206f707573656e630000000001 >
gstreamer-audio_1  | /GstPipeline:pipeline0/GstRtpOPUSPay:rtpopuspay0.GstPad:src: caps = application/x-rtp, media=(string)audio, clock-rate=(int)48000, encoding-name=(string)OPUS, sprop-maxcapturerate=(string)48000, sprop-stereo=(string)0, payload=(int)96, encoding-params=(string)2, ssrc=(uint)4178282910, timestamp-offset=(uint)2882180779, seqnum-offset=(uint)30525
gstreamer-audio_1  | /GstPipeline:pipeline0/GstQueue:queue0.GstPad:sink: caps = application/x-rtp, media=(string)audio, clock-rate=(int)48000, encoding-name=(string)OPUS, sprop-maxcapturerate=(string)48000, sprop-stereo=(string)0, payload=(int)96, encoding-params=(string)2, ssrc=(uint)4178282910, timestamp-offset=(uint)2882180779, seqnum-offset=(uint)30525
gstreamer-audio_1  | /GstPipeline:pipeline0/GstRtpOPUSPay:rtpopuspay0.GstPad:sink: caps = audio/x-opus, rate=(int)48000, channels=(int)1, channel-mapping-family=(int)0, stream-count=(int)1, coupled-count=(int)0, streamheader=(buffer)< 4f707573486561640101380180bb0000000000, 4f707573546167731e000000456e636f6465642077697468204753747265616d6572206f707573656e630000000001 >
gstreamer-audio_1  | /GstPipeline:pipeline0/GstRtpOPUSPay:rtpopuspay0: timestamp = 2882180779
gstreamer-audio_1  | /GstPipeline:pipeline0/GstRtpOPUSPay:rtpopuspay0: seqnum = 30525
gstreamer-audio_1  | /GstPipeline:pipeline0/GstQueue:queue0.GstPad:src: caps = application/x-rtp, media=(string)audio, clock-rate=(int)48000, encoding-name=(string)OPUS, sprop-maxcapturerate=(string)48000, sprop-stereo=(string)0, payload=(int)96, encoding-params=(string)2, ssrc=(uint)4178282910, timestamp-offset=(uint)2882180779, seqnum-offset=(uint)30525
gstreamer-audio_1  | /GstPipeline:pipeline0/GstUDPSink:udpsink0.GstPad:sink: caps = application/x-rtp, media=(string)audio, clock-rate=(int)48000, encoding-name=(string)OPUS, sprop-maxcapturerate=(string)48000, sprop-stereo=(string)0, payload=(int)96, encoding-params=(string)2, ssrc=(uint)4178282910, timestamp-offset=(uint)2882180779, seqnum-offset=(uint)30525
```

Additionnally, as described in the [installation file](https://github.com/ivadim/fruitnanny/blob/master/INSTALLATION.md), I added a new certificate and made sure the Common name is "raspberrypi" since I didn't modify the original host name of my raspberry pi, but I still get a `privacy error` in HTTPS, as the certificate is considered as invalid.

I would be thankful if you have any clue that could help me finish the setup.

Thanks a lot in advance for your time and help!

**Comment by ivadim** [comment]
Hi @chdecultot,
I've just merged #18 which should fix some issues. Try to run `sudo docker-compose up -d` one more time.

**Comment by ivadim** [comment]
`Privacy error` is not easy to solve. Certificate must be generated using public authority like Verisign or you need to update certificate store on each client machine to include self-signed certificate.
Probably, it's not worth it because it only happens on the first request.

**Comment by chdecultot** [comment]
Hi @ivadim,

Thanks a lot for your quick answer!
I have tried again and unfortunately got the same error.
I will continue to analyze what could cause this error and will post it here as soon as I have an explanation.
Have a nice day!

**Comment by ivadim** [comment]
@chdecultot could you please try to run 
* `sudo docker-compose stop` 
* `sudo docker-compose pull` 
* `sudo docker-compose up`

I had an impression that `docker-compose up` should do all of these but I was wrong...

**Comment by chdecultot** [comment]
Hi @ivadim,

Thanks for your feedback. I tried to pull the docker images again, but still have the same error.
I haven't plugged in the temperature sensor in my raspberry yet, do you think it could be the cause of the 500 error ?
